### ISSUE TITLE
Manual installation instructions should mention prerequisites

### ISSUE THREAD

**Issue by Grinnz** [doherty/Dist-Zilla-Plugin-InstallGuide#10]
It's a last resort, but it's probably a good idea to mention that prerequisites will need to be installed first for the manual installation to work. Since at this point we're assuming `cpanm` didn't work, the user could be directed at META.json or META.yml to find what prerequisites they need; or more accurately, at MYMETA.json/MYMETA.yml after the Makefile.PL/Build.PL has been run to generate them.

**Comment by doherty** [comment]
Please feel free to send a patch.

**Comment by doherty** [comment]
9dbe52ca5e240c837991d1db8066c3ecd446600f resolves this
