### ISSUE TITLE
manual "build" and "make" instructions are not portable

### ISSUE THREAD

**Issue by rivy** [doherty/Dist-Zilla-Plugin-InstallGuide#12]
The included instructions for manually building the distribution for both "build" and "make" are not cross-platform compatible. I know they are the usual basic idioms, but they are wrong, specifically for Windows users. But, just a minor modification makes at lease the "build" idiom much more portable.

A portable "build" invocation is ...

```
perl Build.PL
perl Build
perl Build test
perl Build install
```

... or, as a single conditional build line ...

```
perl Build.PL && perl Build && perl Build test && perl Build install
```

"make" instructions are slightly more complicated as the actual `make` is is named differently, even between various windows perl variations (eg, Strawberry perl uses `dmake`). At least an extra notation for Windows users would be helpful, such as ...

```
(On Windows platforms, you should use B<C<dmake>>or B<C<nmake>>, instead of B<C<make>>.)
```

I'm happy to create a PR. But as this is a break from tradition, I wanted to open the discussion first, before blithely throwing out a patch base on solely my opinion.

Your thoughts?

**Comment by doherty** [comment]
Sure, adding an "On Windows..." sentence seems like a good idea. I await a patch `:)`

**Comment by doherty** [comment]
I think 76cfda8c67cc416a959c970a7faa791a0907144f resolves this
