### ISSUE TITLE
Instructions prominently suggest install-as-root options, without mention of non-system-perl solutions

### ISSUE THREAD

**Issue by ap** [doherty/Dist-Zilla-Plugin-InstallGuide#9]
This was always somewhat suboptimal if not questionable, but is now considered bad practice outright.

At the very least the instructions should make passing reference to local::lib and/or perlbrew before moving on to suggest install-as-root incantations.

**Comment by doherty** [comment]
Installing as root is definitely not the only option suggested, so do you mind losing the attitude?

If you'd prefer different instructions be given, let's talk about why and what they should be. Feel free to send a pull request. In particular, I think it'd be appropriate for the instructions to at least include a short discussion of why whipping out sudo is probably not the best answer. Still, it is something that people may do, may need to do, and so I think it's appropriate to let them know how to do it.

**Comment by ap** [comment]
What I meant is the install-as-root stuff is the only approach suggested for if the plain invocation doesn’t work.

I guess the question is who is this `INSTALL` for in your mind? As far as I’m concerned, no Perl developer almost immediately learn to use a CPAN client, and are very unlikely to be going around extracting tarballs except when they need to do something unusual. So to my mind, these instructions are for people who aren’t Perl developers but have downloaded a distro tarball because something else they were trying to install said it need it and now they have this thing extracted to their hard drive and no idea what to do with it. At least that’s the person I was trying to address by adding this plugin to my `dist.ini`s.

For these people, it’s not a good idea to promote an approach that will *work* – by leaving a mess in their system. It needs to at least come with appropriate warning so they’ll know not to try that immediately after their first attempt at installing the module has failed.

For people who know they want to specifically want to install stuff in their system perl, it’s of course fine to include instructions, but that comes back to the audience for this file: I think such people aren’t likely to have to look in `INSTALL` for a reminder of how to do that.

So: let’s say the instructions have been amended to mention install-as-root but to warn against it. And now we have a user who doesn’t know what to do with this tarball. So it tells them they ought to install it with just `cpanm`, but that doesn’t work; and it also tells them they could install it as root, but that they oughtn’t. Now what? Where does that user go from there? The instructions currently do not address this at all.

OTOH, this all rests my assumptions of who the file is for. Maybe your idea of it is different from mine (in which case maybe the right result of this issue would be a patch to the DESCRIPTION of the InstallGuide POD to mention the intended audience explicitly).

**Comment by Grinnz** [comment]
The "sudo" suggestions should definitely be removed; installing to system perl with the CPAN installer is almost never a good idea, and I don't see any audience for which that's a good recommendation.

(The reasons I've compiled for this are:
1) You can cause system libraries to find newer versions of modules than they were expecting,
2) If the package manager upgrades perl, your CPAN-installed modules will be broken,
3) On perls older than 5.12, updates to dual-life modules must overwrite core modules or they will appear not to update due to @INC order)

How to concisely describe usage of local::lib or installing a separate perl to develop with, on the other hand, is a more difficult matter. I think a brief explanation of local::lib may be doable.

**Comment by doherty** [comment]
I think we should probably let the local::lib/perlbrew/etc folks write
their own documentation, and we can provide pointers to it.

Please do send a patch for that.

I do think people generally get into more trouble than they get out of by
shoe-horning sudo in randomly -- let's remove that as well.
